packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true

overrides:
  "@types/node": ^24.7.2
  typescript: ^5.9.3
  tsdown: ^0.15.6

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@prisma/client"
  - "@scarf/scarf"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

sharedWorkspaceLockfile: true
