packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

sharedWorkspaceLockfile: true
