packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@scarf/scarf"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

sharedWorkspaceLockfile: true
