---
name: "Setup Environment"
description: "Checkout, setup PNPM, setup Node using .node-version, and install dependencies"

inputs:
  node-version-file:
    description: "Path to the Node version file"
    required: false
    default: ".node-version"
  cache:
    description: "Cache manager for setup-node"
    required: false
    default: "pnpm"

runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Use NodeJS
      uses: actions/setup-node@v5
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies (frozen)
      run: pnpm install --frozen-lockfile
      shell: bash
