---
name: "Setup Docker"
description: "Setup Docker tools for building and pushing images"

inputs:
  registry:
    description: "Docker registry to push to"
    required: false
  cosign:
    description: "Install cosign"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Install cosign
      if: inputs.cosign == 'true'
      uses: sigstore/cosign-installer@v3

    - name: Check cosign installation
      if: inputs.cosign == 'true'
      run: cosign version
      shell: bash

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: inputs.registry != ''
      uses: docker/login-action@v3.4.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
