---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check-vite-sri-manifest:
    name: Check @oktomusic/vite-sri-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/vite-sri-manifest" build

  eslint:
    name: ESLint (${{ matrix.pkg }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - "@oktomusic/backend"
          - "@oktomusic/frontend"
          - "@oktomusic/lyrics"
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/lyrics
        if: matrix.pkg == '@oktomusic/frontend'
        run: pnpm --filter "@oktomusic/lyrics" build

      - name: Lint package
        run: |
          pnpm --filter "${{ matrix.pkg }}" run lint

  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: build-website
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

      - name: Build & Deploy Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./apps/website/.vitepress/dist --project-name=oktomusic
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
