---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  app-backend:
    name: "@oktomusic/backend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/backend" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/backend" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/backend" run test

  app-frontend:
    name: "@oktomusic/frontend"
    runs-on: ubuntu-latest
    needs: pkg-vite-sri-manifest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/vite-sri-manifest
        run: pnpm --filter "@oktomusic/vite-sri-manifest" build

      - name: Build
        run: pnpm --filter "@oktomusic/frontend" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/frontend" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/frontend" run test

  pkg-vite-sri-manifest:
    name: "@oktomusic/vite-sri-manifest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/vite-sri-manifest" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/vite-sri-manifest" run lint

  pkg-lyrics:
    name: "@oktomusic/lyrics"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/lyrics" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/lyrics" run lint

  website:
    name: "@oktomusic/website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: website
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

      - name: Build & Deploy Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./apps/website/.vitepress/dist --project-name=oktomusic
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
